insert into public.clinics(slug,name,description,whatsapp,phone,address)
values('mavi-pati','Mavi Pati Veteriner Kliniği','Tamamen temsili demo klinik. Fiyatlar ve hizmet bilgileri satış demosu içindir.','905456597551',null,'Demo adres — gerçek işletme değildir')
on conflict(slug) do update set whatsapp=excluded.whatsapp;
insert into public.assistant_knowledge(clinic_id,language_code,category,title,canonical_question,answer_text,keywords,alternative_questions)
select c.id,'tr',v.category,v.question,v.question,v.answer,string_to_array(lower(v.question),' '),array[]::text[] from public.clinics c cross join (values
('Kedi Aşıları','Kedi karma aşısı ne kadar?','Kedi karma aşısı için temsili demo ücretimiz 1.200 TL’dir. Gerçek fiyat değildir.'),
('Kedi Aşıları','Kedi kuduz aşısı ne kadar?','Kedi kuduz aşısı için temsili demo ücretimiz 900 TL’dir. Gerçek fiyat değildir.'),
('Kedi Aşıları','Kedi lösemi aşısı ne kadar?','Kedi lösemi aşısı için temsili demo ücretimiz 1.400 TL’dir. Gerçek fiyat değildir.'),
('Kedi Aşıları','Yavru kediler için aşı planı hazırlıyor musunuz?','Demo kliniğimizde yavru kediler için muayene sonrası veteriner hekimin belirlediği aşı planı hazırlanır.'),
('Köpek Aşıları','Köpek karma aşısı ne kadar?','Köpek karma aşısı için temsili demo ücretimiz 1.300 TL’dir. Gerçek fiyat değildir.'),
('Köpek Aşıları','Köpek kuduz aşısı ne kadar?','Köpek kuduz aşısı için temsili demo ücretimiz 900 TL’dir. Gerçek fiyat değildir.'),
('Köpek Aşıları','Köpek bronşin aşısı ne kadar?','Köpek bronşin aşısı için temsili demo ücretimiz 1.100 TL’dir. Gerçek fiyat değildir.'),
('Köpek Aşıları','Yavru köpekler için aşı planı hazırlıyor musunuz?','Demo kliniğimizde yavru köpeklerin aşı planı muayenede veteriner hekim tarafından belirlenir.'),
('Kısırlaştırma','Kedi kısırlaştırma ücreti nedir?','Kedi kısırlaştırma için temsili demo başlangıç ücreti 4.500 TL’dir. Muayene ve işlem kapsamına göre değişir; gerçek fiyat değildir.'),
('Kısırlaştırma','Köpek kısırlaştırma ücreti nedir?','Köpek kısırlaştırma için temsili demo başlangıç ücreti 6.000 TL’dir. Muayene ve işlem kapsamına göre değişir; gerçek fiyat değildir.'),
('Kısırlaştırma','Kısırlaştırma için randevu gerekli mi?','Demo kliniğimizde kısırlaştırma ön muayenesi ve operasyonu için randevu gereklidir.'),
('Kısırlaştırma','Kısırlaştırma sonrası kontrol yapıyor musunuz?','Demo kliniğimizde operasyon sonrası kontrol randevusu planlanır. Kişisel bakım talimatlarını veteriner hekiminiz verir.'),
('Muayene','Muayene ücreti nedir?','Genel muayene için temsili demo ücretimiz 850 TL’dir. Tetkikler ayrıca değerlendirilir. Gerçek fiyat değildir.'),
('Muayene','Muayeneye gelirken ne getirmeliyim?','Demo kliniğimize gelirken varsa aşı karnesi, önceki tetkikler ve kullanılan ilaçların listesini getirebilirsiniz.'),
('Muayene','Kontrol muayenesi yapıyor musunuz?','Demo kliniğimizde kontrol muayenesi yapılır. Zamanı ve kapsamı veteriner hekiminizle planlanır.'),
('Muayene','Evde muayene hizmetiniz var mı?','Demo kliniğimizde evde muayene hizmeti bulunmamaktadır.'),
('Parazit Uygulamaları','Kedi iç parazit uygulaması ne kadar?','Kedi iç parazit uygulaması için temsili demo başlangıç ücreti 400 TL’dir. Gerçek fiyat değildir.'),
('Parazit Uygulamaları','Köpek iç parazit uygulaması ne kadar?','Köpek iç parazit uygulaması için temsili demo başlangıç ücreti 450 TL’dir. Gerçek fiyat değildir.'),
('Parazit Uygulamaları','Kedi dış parazit uygulaması ne kadar?','Kedi dış parazit uygulaması için temsili demo başlangıç ücreti 500 TL’dir. Gerçek fiyat değildir.'),
('Parazit Uygulamaları','Köpek dış parazit uygulaması ne kadar?','Köpek dış parazit uygulaması için temsili demo başlangıç ücreti 600 TL’dir. Gerçek fiyat değildir.'),
('Mikroçip','Mikroçip uygulaması yapıyor musunuz?','Evet, demo kliniğimizde mikroçip uygulaması hizmeti bulunmaktadır.'),
('Mikroçip','Mikroçip ücreti nedir?','Mikroçip uygulaması için temsili demo ücretimiz 750 TL’dir. Gerçek fiyat değildir.'),
('Mikroçip','Mikroçip kontrolü yapıyor musunuz?','Demo kliniğimizde mikroçip okuyucusu ile çip kontrolü yapılır.'),
('Pasaport','Evcil hayvan pasaportu düzenliyor musunuz?','Demo kliniğimizde evcil hayvan pasaportu işlemleri hakkında destek sunulur. Gerekli belgeler için klinikle görüşün.'),
('Pasaport','Yurt dışı seyahati için destek veriyor musunuz?','Demo kliniğimiz seyahat belgeleri hakkında görüşme sunar. Ülkeye özgü güncel şartlar ilgili resmi makamlarla doğrulanmalıdır.'),
('Pasaport','Aşı karnemi getirmem gerekiyor mu?','Varsa mevcut aşı karnesini ve kimlik belgelerini demo kliniğimize getirmeniz önerilir.'),
('Çalışma Saatleri','Bugün kaça kadar açıksınız?','Temsili demo çalışma saatlerimiz pazartesi–cumartesi 09.00–19.00’dur. Pazar kapalıyız. Tatil günleri için klinikle görüşün.'),
('Çalışma Saatleri','Pazar günü açık mısınız?','Demo kliniğimiz pazar günleri kapalıdır.'),
('Çalışma Saatleri','Sabah kaçta açılıyorsunuz?','Demo kliniğimiz pazartesi–cumartesi sabah 09.00’da açılır.'),
('Acil Hizmet','Acil hizmetiniz var mı?','Demo kliniğimizde 24 saat acil hizmet yoktur. Acil durumda açık bir veteriner kliniğiyle hemen iletişime geçin.'),
('Acil Hizmet','Gece açık mısınız?','Demo kliniğimiz gece açık değildir; temsili kapanış saatimiz 19.00’dur.'),
('Randevu','Randevu almam gerekiyor mu?','Demo kliniğimizde beklemeyi azaltmak için randevu önerilir. Operasyonlar için randevu gereklidir.'),
('Randevu','Nasıl randevu alabilirim?','Demo kliniğimizle WhatsApp üzerinden iletişime geçerek randevu talebinizi paylaşabilirsiniz. Bu asistan randevu oluşturmaz.'),
('Randevu','Randevumu nasıl iptal ederim?','Randevu değişikliği veya iptali için demo kliniğimizle doğrudan iletişime geçin.'),
('Laboratuvar','Kan tahlili yapıyor musunuz?','Demo kliniğimizde veteriner hekimin uygun gördüğü kan tahlilleri yapılır.'),
('Laboratuvar','Tahlil sonuçları ne zaman çıkar?','Demo kliniğimizde sonuç süresi tetkike göre değişir. Kesin süre için klinikle görüşün.'),
('Laboratuvar','İdrar tahlili yapıyor musunuz?','Demo kliniğimizde idrar tahlili hizmeti sunulur; örnek toplama talimatı için klinikle görüşün.'),
('Genel Hizmetler','Kedi ve köpek muayene ediyor musunuz?','Demo kliniğimizde kedi ve köpek muayenesi hizmeti sunulur.'),
('Genel Hizmetler','Tırnak kesimi yapıyor musunuz?','Demo kliniğimizde kedi ve köpekler için tırnak kesimi hizmeti sunulur.'),
('Genel Hizmetler','Hayvan pansiyonu hizmetiniz var mı?','Demo kliniğimizde hayvan pansiyonu hizmeti bulunmamaktadır.')
) as v(category,question,answer) where c.slug='mavi-pati' on conflict(clinic_id,language_code,canonical_question) do nothing;
update public.assistant_knowledge set alternative_questions=array['Kedi karma aşı fiyatı nedir?','Kedi karma aşısı kaç TL?','Kedimin karma aşısını yaptırmak istiyorum.'],keywords=array['kedi','karma','aşısı','fiyat'] where clinic_id=(select id from public.clinics where slug='mavi-pati') and canonical_question='Kedi karma aşısı ne kadar?';
