import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
const knowledgeId = (language, question) => {
  const hex = createHash("sha256")
    .update(`${language}:${question}`)
    .digest("hex")
    .slice(0, 32);
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-4${hex.slice(13, 16)}-8${hex.slice(17, 20)}-${hex.slice(20)}`;
};
const sql = readFileSync(
  new URL("../supabase/seed.sql", import.meta.url),
  "utf8",
);
const clinicFields = sql.match(
  /values\('([^']*)','([^']*)','([^']*)','([^']*)',null,'([^']*)'\)/,
);
if (!clinicFields) throw new Error("Demo clinic seed not found");
const [, slug, name, description, whatsapp, address] = clinicFields;
const clinic = {
  id: "00000000-0000-4000-8000-000000000001",
  slug,
  name,
  description,
  whatsapp,
  address,
  phone: null,
  supported_languages: ["tr", "ru"],
  default_language: "tr",
  name_translations: { ru: "Ветеринарная клиника «Mavi Pati»" },
};
const knowledge = [
  ...sql.matchAll(/^\('([^']*)','([^']*)','([^']*)'\)[,]?$/gm),
].map(([, category, question, answer]) => ({
  id: knowledgeId("tr", question),
  clinic_id: clinic.id,
  language_code: "tr",
  category,
  canonical_question: question,
  answer_text: answer,
  keywords: question.toLocaleLowerCase("tr-TR").split(" "),
  alternative_questions: [],
  priority: 0,
}));
if (knowledge.length !== 40)
  throw new Error(`Expected 40 seed questions, got ${knowledge.length}`);
const override = knowledge.find(
  (k) => k.canonical_question === "Kedi karma aşısı ne kadar?",
);
override.alternative_questions = [
  "Kedi karma aşı fiyatı nedir?",
  "Kedi karma aşısı kaç TL?",
  "Kedimin karma aşısını yaptırmak istiyorum.",
];
override.keywords = ["kedi", "karma", "aşısı", "fiyat"];
const russian = JSON.parse(
  readFileSync(new URL("../supabase/seed/ru.json", import.meta.url), "utf8"),
);
const ruKnowledge = russian.map(
  ([category, sourceQuestion, question, answer, keywords, alternatives]) => {
    if (!knowledge.some((k) => k.canonical_question === sourceQuestion))
      throw new Error(`Missing Turkish counterpart: ${sourceQuestion}`);
    return {
      id: knowledgeId("ru", question),
      clinic_id: clinic.id,
      language_code: "ru",
      category,
      canonical_question: question,
      answer_text: answer,
      keywords,
      alternative_questions: alternatives,
      priority: 0,
    };
  },
);
if (ruKnowledge.length !== 40) throw new Error("Expected 40 Russian questions");
const literal = (value) => `'${value.replaceAll("'", "''")}'`;
const arrayLiteral = (values) =>
  `array[${values.map(literal).join(",")}]::text[]`;
const ruRows = ruKnowledge
  .map(
    (k) =>
      `(${[k.category, k.canonical_question, k.answer_text].map(literal).join(",")},${arrayLiteral(k.keywords)},${arrayLiteral(k.alternative_questions)})`,
  )
  .join(",\n");
writeFileSync(
  new URL("../supabase/seed-ru.sql", import.meta.url),
  `-- Generated by scripts/generate-demo.mjs. Run after both migrations and seed.sql.\nbegin;\nupdate public.clinics set supported_languages=array['tr','ru'],default_language='tr',name_translations=name_translations || '{"ru":"Ветеринарная клиника «Mavi Pati»"}'::jsonb where slug='mavi-pati';\ninsert into public.assistant_knowledge(clinic_id,language_code,category,title,canonical_question,answer_text,keywords,alternative_questions)\nselect c.id,'ru',v.category,v.question,v.question,v.answer,v.keywords,v.alternatives from public.clinics c cross join (values\n${ruRows}\n) as v(category,question,answer,keywords,alternatives) where c.slug='mavi-pati'\non conflict(clinic_id,language_code,canonical_question) do update set category=excluded.category,answer_text=excluded.answer_text,keywords=excluded.keywords,alternative_questions=excluded.alternative_questions;\ncommit;\n`,
);
mkdirSync(new URL("../lib/demo/", import.meta.url), { recursive: true });
writeFileSync(
  new URL("../lib/demo/seed.json", import.meta.url),
  JSON.stringify(
    { clinic, knowledge: [...knowledge, ...ruKnowledge] },
    null,
    2,
  ) + "\n",
);
